Daniel school
ucsb-cs156-s24/proj-organic-s24-5pm-1 pull request #14
Opened 2024-05-24 01:37 UTC by JUstISAGE

2024-05-24 01:53 UTC, Peak1260 approved these changes, later dismissed
LGTM

2024-05-25 03:30 UTC, pconrad commented
It's not working for me on https://proj-school-daniel-dev.dokku-09.cs.ucsb.edu/

This is what I'm seeing:

![create-school](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/assets/1119017/2ff756e0-86c2-43cd-a4be-756532857f10)

2024-05-25 03:36 UTC, pconrad requested changes
Please remove:
* the commented out code
* the unnecessary changes to the backend.  They are not needed, and even if they were, they should be in a separate PR (but they are NOT needed.)

Finally: it isn't working for me on dokku.  So even if the issues above are addressed, you also need to figure out why it isn't working.

2024-05-25 03:36 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/organic/controllers/SchoolController.java
> +    @DeleteMapping("/delete")
```suggestion
    @DeleteMapping("")
```

This is fine. There is not need to add `/delete`

2024-05-25 03:36 UTC, pconrad commented on src/test/java/edu/ucsb/cs156/organic/controllers/SchoolControllerTests.java
> +        MvcResult response = mockMvc.perform(get("/api/schools/get").param("abbrev", "umn")).andExpect(status().isNotFound())
Please restore the old code.

2024-05-25 03:40 UTC, pconrad requested changes
Please fix the title also.

see: https://ucsb-cs156.github.io/topics/pull_requests/#pr-titles

2024-05-27 21:02 UTC, rtzhang1x commented
> It's not working for me on https://proj-school-daniel-dev.dokku-09.cs.ucsb.edu/
> 
> This is what I'm seeing:
> 
> ![create-school](https://private-user-images.githubusercontent.com/1119017/333769206-2ff756e0-86c2-43cd-a4be-756532857f10.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NDI0ODAsIm5iZiI6MTcxNjg0MjE4MCwicGF0aCI6Ii8xMTE5MDE3LzMzMzc2OTIwNi0yZmY3NTZlMC04NmMyLTQzY2QtYTRiZS03NTY1MzI4NTdmMTAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjdUMjAzNjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDdhNmU4ZjAyNzg4ZGIyZTA2MTQ4NGE4MzkzZTI5MTlhNmQ2ZWQ5OThkNGVlNmZkZWY2Y2UxZjg1ZDg0MmU4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qhqXH7_Q7DnegfrWuohokUSJGNPEkGyN9RJcIS7gO60)

![image](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/assets/50055753/a2a83617-df72-484f-82c4-0f147dea5ba7)

The same things happens in my localhost. Above is the error that occured. Maybe the brackets or the backslash (which is usually used as an escape character) is causing the illegal argument exception.

2024-05-27 21:05 UTC, rtzhang1x commented
> > It's not working for me on https://proj-school-daniel-dev.dokku-09.cs.ucsb.edu/
> > This is what I'm seeing:
> > ![create-school](https://private-user-images.githubusercontent.com/1119017/333769206-2ff756e0-86c2-43cd-a4be-756532857f10.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NDI0ODAsIm5iZiI6MTcxNjg0MjE4MCwicGF0aCI6Ii8xMTE5MDE3LzMzMzc2OTIwNi0yZmY3NTZlMC04NmMyLTQzY2QtYTRiZS03NTY1MzI4NTdmMTAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjdUMjAzNjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDdhNmU4ZjAyNzg4ZGIyZTA2MTQ4NGE4MzkzZTI5MTlhNmQ2ZWQ5OThkNGVlNmZkZWY2Y2UxZjg1ZDg0MmU4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qhqXH7_Q7DnegfrWuohokUSJGNPEkGyN9RJcIS7gO60)
> 
> ![image](https://private-user-images.githubusercontent.com/50055753/334211282-a2a83617-df72-484f-82c4-0f147dea5ba7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NDQwMzYsIm5iZiI6MTcxNjg0MzczNiwicGF0aCI6Ii81MDA1NTc1My8zMzQyMTEyODItYTJhODM2MTctZGY3Mi00ODRmLTgyYzQtMGYxNDdkZWE1YmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDIxMDIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2Y2JjNGI2NWJjOTIzZTQyODhhNDY3ZmUzYzE3YzYwNjM3ZDE3ZjI0Mjc3ZDNkNzI3ZjM5NzM3MzA3OWM2YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M3QifZ2P3nzy1HGJlYHy41z4b0KM5qiZTUOwcm6hNnY)
> 
> The same things happens in my localhost. Above is the error that occured. Maybe the brackets or the backslash (which is usually used as an escape character) is causing the illegal argument exception.

Caused by these lines?
![image](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/assets/50055753/67bb14bd-e005-4636-86e2-d0f9ea57ecf2)

Looking at school.java, it turns out `school.getTermRegex()` **DOES NOT EXIST**!!!

2024-05-27 21:25 UTC, rtzhang1x requested changes
Right now is to figure out how to bypass the invalid character error and create an actual implementation for `school.getTermRegex()`. These are the breaking parts of this pull request right now.
After that, we don't even know if your table interface is functional right now.

2024-05-27 21:28 UTC, JUstISAGE commented
> Right now is to figure out how to bypass the invalid character error and create an actual implementation for `school.getTermRegex()`. These are the breaking parts of this pull request right now. After that, we don't even know if your table interface is functional right now.

I encodes the url manually and solved this problem, but a frontend test failed for some reasons

2024-05-28 00:13 UTC, Crossover661 commented
Looks good to me.

2024-05-28 00:13 UTC, Crossover661 reviewed
Looks good to me.

2024-05-28 01:16 UTC, merged