DRAFT - Course Show Page
ucsb-cs156-s24/proj-organic-s24-5pm-1 pull request #20
Opened 2024-05-27 23:57 UTC by Peak1260

In this pull request, I implemented a course show page that will allow admins and instructors to have a look at individual course information. I created a show button which will link you to that page. There is also a short description to let the admins/instructors know what to do on this page, and links created to add students, staff, or class rosters though those are not linked to anything yet as it is for future implementation. The testing currently isn't at 100% coverage so that is what I need help on now.

Dokku deployment:
https://proj1-peak1260-dev.dokku-09.cs.ucsb.edu/

Page image:
![Screenshot 2024-05-27 165016](https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/assets/92136161/b719dec2-8932-4ba4-a173-187f9a9cc066)

2024-05-28 00:37 UTC, pconrad commented on frontend/src/main/pages/CoursesShowPage.js
> +        useBackend(
```suggestion
       // Stryker disable all 
        useBackend(
```

2024-05-28 00:40 UTC, pconrad reviewed
A few suggestions

2024-05-28 00:40 UTC, pconrad commented on frontend/src/main/pages/CoursesShowPage.js
> +        );
```suggestion
        );
        // Stryker restore all
```

2024-05-28 00:40 UTC, pconrad commented on frontend/src/main/pages/CoursesShowPage.js
> +                <CoursesTable courses={checkLength} currentUser={currentUser} />
```suggestion
                <CoursesTable courses={course ? [course] : []} currentUser={currentUser} />
```

This says: if you have one course, put it in an array which is what the CoursesTable expects.  If you don't have one course, then just display an empty list.

2024-05-28 03:58 UTC, rtzhang1x commented
I should probably leave that commit in a seperate branch...
https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/pull/24

2024-05-29 01:06 UTC, sanilkatula commented
It's good.

One suggestion - when we go to the Show page lets keep the info limited. 

<img width="617" alt="Screenshot 2024-05-28 at 6 04 18 PM" src="https://github.com/ucsb-cs156-s24/proj-organic-s24-5pm-1/assets/124859948/6e65b329-7126-4c60-8e21-3384eab4d96d">

instead of show, staff, edit, delete, etc all these button. 

Let's stay with the edit button only. And at max the staff button because the below upload staff is not implemented.

2024-05-29 01:06 UTC, sanilkatula requested changes
see comment

2024-05-29 23:59 UTC, sanilkatula submitted a review, later dismissed

2024-05-30 00:00 UTC, sanilkatula commented
LGTM

2024-05-30 01:03 UTC, GeorgebigG submitted a review, later dismissed
LGTM!

2024-05-30 01:40 UTC, pconrad requested changes
Please remove all links to pages that are not yet implemented, or else put in placeholder pages.  

We don't merge code into main with buttons or links that lead to error messages. That's not good practice.  The main branch shouldn't have known bugs in it.

2024-05-30 03:12 UTC, Peak1260 commented
Hyperlinks are now removed.

2024-05-30 03:16 UTC, JUstISAGE approved these changes
LGTM

2024-05-30 17:38 UTC, pconrad approved these changes
LGTM.   Staff button still leads to a non-existing page, but I know it's coming so I'll let it slide.

2024-05-30 17:38 UTC, merged