Dropdown frontend
ucsb-cs156-s24/proj-organic-s24-5pm-1 pull request #22
Opened 2024-05-28 01:08 UTC by ylin250

testing, will not pass tests, just to see errors

2024-05-29 19:24 UTC, ylin250 commented
dokku:https://proj-ylin250.dokku-09.cs.ucsb.edu/
This pr changed course creation from entering school as text into selecting a dropdown menu of schools.
After creating component for the dropdown in frontend, api calls were made to feed the information from backend into the array of school names for the dropdown to be displayed. Some tests and other files are modified to accommodate for the change.

2024-05-30 02:27 UTC, JUstISAGE approved these changes, later dismissed
LGTM!

2024-05-30 17:40 UTC, pconrad commented on frontend/src/App.js
>      </>
It looks llike you are removing the schools index and replacing it with /courses/create.

Are you really sure that's what you want to do here?

2024-05-30 17:40 UTC, pconrad commented on frontend/src/main/components/Courses/CoursesForm.js
> +// import { schoolsFixtures } from "fixtures/schoolsFixtures.js";
Commented out code

2024-05-30 17:42 UTC, pconrad commented on frontend/src/tests/components/Courses/CoursesForm.test.js
> +    // Added this test to address the mutation testing issue
I don't think this comment really adds any value for future developers.

This is the kind of thing you can comment on in the PR if you want to document it for folks reviewing your code. 

In particular: line numbers are going to change, so as my former boss at AppFolio likes to say, this comment is a "lie waiting to happen".

2024-05-30 17:44 UTC, pconrad requested changes
I'm having trouble testing this since the dokku deployment doesn't seem to have a place for creating courses.

I'm also confused about "selecting classes" in the title.  Where is there a use case in this app for  selecting classes?  Do you mean schools.

Several more things to address:
* You seem to be removing a route for the SchoolsIndexPage.  Are you sure you want to do that?
* Some comments that don't seem to add value.  See the details in the code review.
* Finally: please read: https://ucsb-cs156.github.io/topics/pull_requests/package_lock_json.html and make the necessary adjustments to this PR.

2024-05-31 05:37 UTC, JUstISAGE submitted a review, later dismissed
LGTM

2024-06-06 02:49 UTC, ylin250 commented
after looking through dokku logs, We reached the conclusion that it's likely that deployed postgres database doesn't have auto increment capability

2024-06-06 21:50 UTC, ylin250 commented
PR description has been fixed, please take a look

2024-06-07 03:00 UTC, pconrad commented
Replaced by #39

2024-06-07 03:00 UTC, closed without merging