Added api/staff/all for the backend
ucsb-cs156-s24/proj-organic-s24-5pm-1 pull request #26
Opened 2024-05-29 00:17 UTC by GeorgebigG

For the staff I am adding api/staff/all that lists every staff member

https://organic-george.dokku-09.cs.ucsb.edu

2024-05-29 00:23 UTC, JUstISAGE approved these changes
LGTM

2024-05-30 01:22 UTC, pconrad requested changes
This is not useful in its current form.

An endpoint for getting all staff for a given course, though, would be useful.

2024-05-30 01:22 UTC, pconrad commented on src/main/java/edu/ucsb/cs156/organic/controllers/StaffController.java
> +}
We actually don't want or need this route.

What we need is a route that returns all staff for a given course.

There is no use case for "all staff across all courses".

2024-05-30 19:11 UTC, closed without merging

2024-05-30 19:12 UTC, GeorgebigG commented
Unfortunately I made a mistake with this pull request. I coded staff/all backend which apparently we didn't need