Removed TermError from the UX
ucsb-cs156-s24/proj-organic-s24-5pm-1 pull request #30
Opened 2024-05-30 00:34 UTC by GeorgebigG

Removed TermError from the UX (from the form and table for course).

2024-05-30 01:56 UTC, JUstISAGE approved these changes, later dismissed
LGTM

2024-05-30 17:57 UTC, pconrad requested changes
Please remove commented out code when merging into main.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-30 17:57 UTC, pconrad commented on frontend/src/tests/components/School/SchoolForm.test.js
> +        // expect(screen.getByText(/Term Error is required./)).toBeInTheDocument();
Please remove commented out code when merging into main.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-30 17:57 UTC, pconrad commented on frontend/src/tests/components/School/SchoolForm.test.js
> +        // const termErrorField = screen.getByTestId("SchoolForm-termError");
Please remove commented out code when merging into main.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-30 17:57 UTC, pconrad commented on frontend/src/tests/components/School/SchoolForm.test.js
> +        // fireEvent.change(termErrorField, { target: { value: 'Quarter must be entered in the correct format' } });
Please remove commented out code when merging into main.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-30 17:57 UTC, pconrad commented on frontend/src/tests/components/School/SchoolForm.test.js
> +        // expect(screen.queryByText(/Term Error is required./)).not.toBeInTheDocument();
Please remove commented out code when merging into main.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-30 17:57 UTC, pconrad commented on frontend/src/tests/pages/SchoolCreatePage.test.js
> +            // termError: "error-1"
Please remove commented out code when merging into main.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-30 17:57 UTC, pconrad commented on frontend/src/tests/pages/SchoolCreatePage.test.js
> +        // const termErrorField = screen.getByTestId("SchoolForm-termError");
Please remove commented out code when merging into main.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-30 17:57 UTC, pconrad commented on frontend/src/tests/pages/SchoolCreatePage.test.js
> +        // fireEvent.change(termErrorField, { target: { value: 'error-1' } });
Please remove commented out code when merging into main.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-30 17:57 UTC, pconrad commented on frontend/src/tests/pages/SchoolCreatePage.test.js
> +                // "termError": "error-1"
Please remove commented out code when merging into main.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-30 17:57 UTC, pconrad commented on frontend/src/tests/pages/SchoolEditPage.test.js
> +            // const termErrorField = screen.getByTestId("SchoolForm-termError");
Please remove commented out code when merging into main.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-30 17:57 UTC, pconrad commented on frontend/src/tests/pages/SchoolEditPage.test.js
> +            // expect(termErrorField).toHaveValue("error-17");
Please remove commented out code when merging into main.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-30 17:57 UTC, pconrad commented on frontend/src/tests/pages/SchoolEditPage.test.js
> +            // fireEvent.change(termErrorField, { target: { value: 'new-error-17' } });
Please remove commented out code when merging into main.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-30 17:57 UTC, pconrad commented on frontend/src/tests/pages/SchoolEditPage.test.js
> +            // const termErrorField = screen.getByTestId("SchoolForm-termError");
Please remove commented out code when merging into main.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-30 17:57 UTC, pconrad commented on frontend/src/tests/pages/SchoolEditPage.test.js
> +            // expect(termErrorField).toHaveValue("error-17");
Please remove commented out code when merging into main.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-30 17:57 UTC, pconrad commented on frontend/src/tests/pages/SchoolEditPage.test.js
> +            // fireEvent.change(termErrorField, { target: { value: 'new-error-17' } });
Please remove commented out code when merging into main.
See: https://ucsb-cs156.github.io/topics/code_reviews/commented_out_code.html

2024-05-30 19:26 UTC, Peak1260 approved these changes
Looks like the unnecessary comments were taken out and everything looks good

2024-05-31 21:54 UTC, pconrad approved these changes
LGTM

2024-05-31 21:57 UTC, pconrad approved these changes
LGTM

2024-05-31 21:57 UTC, merged