Added explanations to School Form
ucsb-cs156-s24/proj-organic-s24-5pm-1 pull request #32
Opened 2024-05-31 00:40 UTC by GeorgebigG

For the abbrev, I added an saying that abbreviations should be all lowercase. I added a term regex [WSMF]\d\d for UCSB since our terms are for example: F24, W25, S25, M25. And I changed the term description.

https://organic-george.dokku-09.cs.ucsb.edu/

2024-05-31 00:42 UTC, Crossover661 reviewed
Looks good to me, except please fix the errors in the testing (unit tests, coverage, stryker).

2024-05-31 01:19 UTC, Crossover661 reviewed
Looks good to me! Errors have been fixed.

2024-05-31 05:36 UTC, JUstISAGE submitted a review, later dismissed
lgtm

2024-05-31 22:03 UTC, pconrad commented on frontend/src/main/components/School/SchoolForm.js
> +                            {errors.termRegex && 'Term Regex has to include a single character for a Quarter and 2 digits for the year.'}
```suggestion
                            {errors.termRegex && 'Term regex is required.'}
```

2024-05-31 22:03 UTC, pconrad commented on frontend/src/main/components/School/SchoolForm.js
> +                            {...register("termRegex", { required: true, pattern: term_regex })}
```suggestion
                            {...register("termRegex", { required: true})}
```

This is applying the regular expression `const term_regex = /[WSMF]\d\d/;` to the input for this field, which completely misunderstands what is supposed to be happening here.

Instead, we want the user to *input the regular expression against which the terms for their school will be matched*.

That is, if your schools has terms likes F24, W25, S25, M25 then your regex is `[FMSW]\d\d`.  And it should be used to validate the input of the term on the *course entry form*, not anything else.

But, we probably cannot come up with a "regex for regexes" so instead, we leave this required but we don't validate it with a regex.

2024-05-31 22:03 UTC, pconrad commented on frontend/src/main/components/School/SchoolForm.js
> +    const term_regex = /[WSMF]\d\d/;
```suggestion
```

Remove this; see below.

2024-05-31 22:21 UTC, pconrad requested changes
It appears that your understanding of the purpose of the "term regex" field is not aligned with the intention of that field.

Here's the idea: UCSB uses terms abbreviations such as F24, W25, S25, and M25.

A regular expression for validating those is '[FWMS]\d\d'.

But Washington State University, which has semesters, uses: Fa24, Sp25, Su25, etc.

A regular expression for that would '(Fa|Sp|Su)\d\d'.

So what we want is guidance for the user that helps them understand that.  The first thing we have to do is make sure *we* are on the same page about that.

I've added some suggestions in the code below, but I also want to ask you to look at the the [CommonsForm](https://github.com/ucsb-cs156/proj-happycows/blob/e7487fca555481a59c9ab47d9583b3d2cc8f4a01/frontend/src/main/components/Commons/CommonsForm.js#L112C25-L125C42) from proj-happycows, and the Tooltips in that form. That's what I'm asking for here.   


Specifically, add `OverlayTrigger, Tooltip` in the import for `react-bootstrap`:

```
import {Button, Form, Row, Col, OverlayTrigger, Tooltip} from "react-bootstrap";
```


Then use code such as this from [here](https://github.com/ucsb-cs156/proj-happycows/blob/e7487fca555481a59c9ab47d9583b3d2cc8f4a01/frontend/src/main/components/Commons/CommonsForm.js#L112C25-L125C42).  Note how the `<OverlayTrigger>` surrounds the  `<Form.Control>` element, and the `<Tooltip>` is inside it.

```
<OverlayTrigger
                            placement="top"
                            overlay={<Tooltip>This is the name farmers will see when joining the game.</Tooltip>}
                            delay='5'
                        >
                            <Form.Control
                                data-testid={`${testid}-name`}
                                id="name"
                                type="text"
                                defaultValue={DefaultVals.name}
                                isInvalid={!!errors.name}
                                {...register("name", {required: "Commons name is required"})}
                            />
                        </OverlayTrigger>
```

For Abbreviation, the tooltip could be something like:
```
Please choose an abbreviation for your school such as ucsb, wsu, uh-hilo, etc, consisting of only lowercase characters and hyphens.
```

For Name:
```
The normal full name by which your school is known, e.g. UC Santa Barbara, U Hawaii - Hilo, Washington State, Oregon State, etc.
```

For Term Regex
```
Enter a regular expression that can be used for the abbreviations for academic terms at your school.  For example, if your terms are F24, W25, S25, M25, you can use [FWSM]\d\d.  To allow anything to be entered, use .* for this field.
```

For term description:
```
Please enter the name of the academic term used at your school.  For example: Semester, Quarter, Session, etc.
```

2024-05-31 22:21 UTC, pconrad commented on frontend/src/main/components/School/SchoolForm.js
> +                        <Form.Label htmlFor="abbrev">Abbreviation(All lowercase)</Form.Label>
```suggestion
                        <Form.Label htmlFor="abbrev">Abbreviation (all lowercase)</Form.Label>
```

2024-05-31 22:21 UTC, pconrad commented on frontend/src/main/components/School/SchoolForm.js
> +                        <Form.Label htmlFor="termDescription">Term Description(Quarter, Semester or Session)</Form.Label>
```suggestion
                        <Form.Label htmlFor="termDescription">Term Description (e.g. Quarter, Semester, Session)</Form.Label>
```

2024-05-31 22:21 UTC, pconrad commented on frontend/src/tests/components/School/SchoolForm.test.js
> +        expect(screen.getByText(/Term Regex has to include a single character for a Quarter and 2 digits for the year./)).toBeInTheDocument();
```suggestion
        expect(screen.getByText(/Term Regex is required./)).toBeInTheDocument();
```

2024-05-31 22:21 UTC, pconrad commented on frontend/src/tests/pages/SchoolCreatePage.test.js
> +        fireEvent.change(termRegexField, { target: { value: 'W24' } });
```suggestion
        fireEvent.change(termRegexField, { target: { value: "[WSMF]\\d\\d" } });
```

2024-05-31 22:21 UTC, pconrad commented on frontend/src/tests/pages/SchoolCreatePage.test.js
> +                "termRegex": "W24",
```suggestion
                "termRegex": "[WSMF]\\d\\d" ,
```

2024-06-02 06:36 UTC, JUstISAGE approved these changes
lgtm

2024-06-02 06:36 UTC, Peak1260 approved these changes
LGTM

2024-06-02 06:36 UTC, ylin250 approved these changes
LGTM!

2024-06-04 22:57 UTC, pconrad commented on frontend/src/main/components/School/SchoolForm.js
> +                        <Form.Label htmlFor="termRegex">Term Regex(Example: W24)</Form.Label>
```suggestion
                        <Form.Label htmlFor="termRegex">Term Regex (Example: [WSMF]\d\d)</Form.Label>
```

2024-06-04 22:57 UTC, pconrad approved these changes
Technically, there's still one issue with this PR, but I'm going to let it go because we are running out of time.   If you want to make a very quick PR to fix it before class ends tonight, I'll consider merging it; otherwise it will just have to stay like this and we'll fix it later.

2024-06-04 22:58 UTC, merged